### ISSUE TITLE
Ability to output a color value from a variable

### ISSUE THREAD

**Issue by willemdewit** [SassDoc/sassdoc-theme-default#28]
It would be nice if the sassdoc detected that a color is being used as a value of a variable. It should then output a tile with the configured color.

    /**
     * The theme color used for creating a color range.
     * @type color
     */
    $theme-color: rgb(85,128,182) !default;

**Comment by ben-eb** [comment]
I think we need something in JS rather than SCSS for this, given that I was just outputting the colour into a span element. Perhaps a swig filter that could calculate an appropriate background value?

**Comment by HugoGiraudel** [comment]
Agreed.

**Comment by ben-eb** [comment]
:+1:

OK, can do that. Which do you prefer; the background colour of the value being the hex colour, or the text colour itself being the hex colour?

**Comment by HugoGiraudel** [comment]
I think the text color being the color itself would be good. Accurate workflow would be to compute the luminance of a color (with a Swig filter), and if it's higher than 0.8, print a dark background (something like #333).

```twig
{% if (prop.type|lower).indexOf('color') and prop.default %}
  <code
    style="color: {{ prop.default }};"
    {% if prop.default|luminance > .8 %}class="dark"{% endif %}
  >{{ prop.default }}</code>
{% else %}
  <code>{{ prop.default }}</code>
{% endif %}
```

Might need adjustments.

**Comment by ben-eb** [comment]
My idea was to run the value through the YIQ algorithm and then just have `#000` or `#fff` as the background colour; it gives the best contrast for the text. Classes might be better though, what do you think?

```twig
<code style="background:{{ prop.default | yiq }}; color: {{ prop.default }}">{{ prop.default }}</code>
```

**Comment by HugoGiraudel** [comment]
Anyway, you have to make sure it is a color. But that sounds good however.

**Comment by ben-eb** [comment]
Awesome. :smiley:

**Comment by willemvb** [comment]
Would this work for Colors in a map as well?

``` sass
/// Orange tints
/// @group Colors
/// @type Map
/// @prop {String} key - tint name
/// @prop {Color} value - color
$orange: (
  lightest: #ffe5ca,
  lighter: #f5b180,
  light: #e77636,
  default: #e13400,
  dark: #711f03,
  darker: #581902,
  darkest: #391102,
);
```

**Comment by HugoGiraudel** [comment]
Sure. :)

**Comment by willemvb** [comment]
Should it work in 2.1.1? I'm only seeing map values in my output, and no swatches.
No idea what I'm doing wrong. Any help is appreciated!

![screen shot 2015-02-27 at 09 38 44](https://cloud.githubusercontent.com/assets/1336390/6409461/7961e644-be64-11e4-91ac-741c5056b01f.png)

**Comment by HugoGiraudel** [comment]
Color previews are not displayed in the code block but in the property table. You might want to change your doc as follow:

```scss
/// Orange tints
/// @group Colors
/// @type Map
/// @prop {Color} lightest [#ffe5ca]
/// @prop {Color} lighter [#f5b180]
/// @prop {Color} light [#e77636]
/// @prop {Color} default [#e13400]
/// @prop {Color} dark [#711f03]
/// @prop {Color} darker [#581902]
/// @prop {Color} darkest [#391102]
$orange: (
  lightest: #ffe5ca,
  lighter: #f5b180,
  light: #e77636,
  default: #e13400,
  dark: #711f03,
  darker: #581902,
  darkest: #391102,
);
```
