### ISSUE TITLE
grouped item linking issue

### ISSUE THREAD

**Issue by lukassero** [SassDoc/sassdoc-theme-default#85]
A placeholder is grouped in @buttons
```
/// Button generic styles
/// @group Buttons
%bttn-generic {}
```
When I click on it in left side bar it anchors to 
```
./index.html#buttons-placeholder-bttn-generic
```
and it is fine.

But when I navigate to the variable that is used by the very same placeholder and click on ‘Used by’ link it anchors to 
```
./index.html#placeholder-bttn-generic
```
which is incorrect.

Same applies to all documented items that were grouped.

My config .sassdocrc file:
```
exclude:
  - sass/vendor/*
shortcutIcon: static/img/favicon.ico
groups:
  buttons: Buttons
  color-palette: Color Palette
  buttons: Buttons
  labels: Labels
  font-family: Font Family
  undefined: General
```
