### ISSUE TITLE
Shouldn't mixin output be placed after example?

### ISSUE THREAD

**Issue by marcohamersma** [SassDoc/sassdoc-theme-default#93]
Hey hey,
I see that in the default theme the [output for a mixin is placed before output](https://github.com/SassDoc/sassdoc-theme-default/blob/master/default.json#L5). 

To me it would make more sense to show the example first, and then the output that example results in. For example:

**Example:**

``` scss
@include foo-bar('red');
```

**Output**

``` css
.baz {
  border: 1px red;
  color: red;
  text-transform: uppercase;
}
```

Is there a use case I'm overseeing in which output would make sense to put before the example?

Cheers,
Marco
